In [1]:
import numpy as np

In [2]:
첫번째밭 = [
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1]
]

두번째밭 = [
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 3],
    [0, 0, 0, 0, 4],
    [0, 2, 0, 0, 2],
    [4, 5, 0, 2, 0]
]

In [3]:
첫번째밭

[[1, 0, 0, 0, 0],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 0, 1]]

In [4]:
두번째밭

[[0, 0, 0, 0, 1],
 [0, 0, 0, 0, 3],
 [0, 0, 0, 0, 4],
 [0, 2, 0, 0, 2],
 [4, 5, 0, 2, 0]]

In [5]:
# 시계방향으로 돌리고 싶으면 -1
np.rot90(두번째밭, 1)

array([[1, 3, 4, 2, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 2, 5],
       [0, 0, 0, 0, 4]])

In [6]:
np.rot90(두번째밭, 1) + np.array(첫번째밭)

array([[2, 3, 4, 2, 0],
       [0, 0, 1, 0, 3],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 2, 6],
       [0, 0, 1, 0, 5]])

In [7]:
np.rot90(두번째밭, 1) - np.array(첫번째밭)

array([[ 0,  3,  4,  2,  0],
       [ 0,  0, -1,  0,  1],
       [ 0,  0, -1,  0, -1],
       [ 0,  0, -1,  2,  4],
       [ 0,  0, -1,  0,  3]])

In [8]:
np.rot90(두번째밭, 1) * np.array(첫번째밭)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 4]])

In [10]:
np.rot90(두번째밭, 1) @ np.array(첫번째밭)

array([[1, 0, 9, 0, 9],
       [0, 0, 2, 0, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 7, 0, 7],
       [0, 0, 4, 0, 4]])

In [11]:
정답 = np.rot90(두번째밭, 1) + np.array(첫번째밭)

In [15]:
정답

array([[2, 3, 4, 2, 0],
       [0, 0, 1, 0, 3],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 2, 6],
       [0, 0, 1, 0, 5]])

In [14]:
정답[0]

array([2, 3, 4, 2, 0])

In [13]:
[i for i in 정답[0]]

[2, 3, 4, 2, 0]

In [18]:
''.join([str(i) for i in 정답[0]])

'23420'

In [21]:
int(''.join([str(i) for i in 정답[0]]),8)

10000

In [26]:
for k in range(5):
    print(chr(int(''.join([str(i) for i in 정답[k]]),8)))

✐
C
A
V
E


# numpy 없이 풀기

In [35]:
sample = [
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
]

첫번째밭 = [
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 1, 0, 1]
]

두번째밭 = [
    [0, 0, 0, 0, 1],
    [0, 0, 0, 0, 3],
    [0, 0, 0, 0, 4],
    [0, 2, 0, 0, 2],
    [4, 5, 0, 2, 0]
]

In [33]:
x = [[None]*5]*5
x

[[None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None],
 [None, None, None, None, None]]

In [34]:
x[0][0] = 1000
x

[[1000, None, None, None, None],
 [1000, None, None, None, None],
 [1000, None, None, None, None],
 [1000, None, None, None, None],
 [1000, None, None, None, None]]

In [36]:
sample

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [39]:
두번째밭

[[0, 0, 0, 0, 1],
 [0, 0, 0, 0, 3],
 [0, 0, 0, 0, 4],
 [0, 2, 0, 0, 2],
 [4, 5, 0, 2, 0]]

In [50]:
for i in range(len(두번째밭)): #행
    for j in range(len(두번째밭[0])):
        sample[i][j] = 두번째밭[j][len(두번째밭)-1-i]
        
sample

[[1, 3, 4, 2, 0],
 [0, 0, 0, 0, 2],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 2, 5],
 [0, 0, 0, 0, 4]]

In [57]:
sample + 첫번째밭

[[1, 3, 4, 2, 0],
 [0, 0, 0, 0, 2],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 2, 5],
 [0, 0, 0, 0, 4],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 0, 1]]

In [59]:
for i in range(len(두번째밭)):
    for j in range(len(두번째밭[0])):
        sample[i][j] += 첫번째밭[i][j]
        
sample

[[2, 3, 4, 2, 0],
 [0, 0, 1, 0, 3],
 [0, 0, 1, 0, 1],
 [0, 0, 1, 2, 6],
 [0, 0, 1, 0, 5]]